apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubegres
  namespace: flux-system
spec:
  targetNamespace: kubegres
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: kubegres
  path: ./kubegres.yaml
  prune: true
  wait: true
  timeout: 5m0s