apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-manifests
  namespace: argocd
spec:
  interval: 1m0s
  targetNamespace: argocd
  sourceRef:
    kind: GitRepository
    name: app-manifests
  path: "./apps"
  prune: true